### ISSUE TITLE
Supporting CTAP2.0 protocol.

### ISSUE THREAD

**Issue by alishir** [MattGorko/libu2f-emu#6]
Hi César,

Do you have any plan to support [CTAP2.0](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html) protocol?

**Comment by rgl** [comment]
Why did you close this issue? Does this already implements ctap2.0? Is that version what permits the use of the passwordless mode?
